name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build-prod
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Function Dependencies
        run: npm install
        working-directory: functions
      - run: 'echo "$CREDENTIALS_JSON" > service-account.json'
        shell: bash
        working-directory: functions
        env:
          SSH_KEY: ${{secrets.CREDENTIALS_JSON}}
      - run: 'echo "$OAUTH_CONFIG" > info.js'
        shell: bash
        working-directory: functions
        env:
          SSH_KEY: ${{secrets.OAUTH_CONFIG}}
      - run: 'echo "$TEST_JSON" > test.json'
        shell: bash
        working-directory: functions
        env:
          SSH_KEY: ${{secrets.TEST_JSON}}
      - run: echo "$(cat test.json)"
        working-directory: functions
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
