name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build-prod
      - name: Upload dist/ folder with built files
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download dist/ folder
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Install Function Dependencies
        run: npm install
        working-directory: functions
      - run: 'echo "$CREDENTIALS_JSON" > service-account.json'
        shell: bash
        working-directory: functions
        env:
          CREDENTIALS_JSON: ${{secrets.CREDENTIALS_JSON}}
      - run: 'echo "$OAUTH_CONFIG" > info.js'
        shell: bash
        working-directory: functions
        env:
          OAUTH_CONFIG: ${{secrets.OAUTH_CONFIG}}
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
